### ISSUE TITLE
Question: ECC GPG signing key support on Terraform Registry API

### ISSUE THREAD

**Issue by hirosassa** [hashicorp/terraform-docs-common#106]
Hi,

I would like to use ECC GPG signing key because it is safer than RSA, DSA keys. 
But, currently, Terraform Registry API [doesn't support it](https://www.terraform.io/registry/providers/publishing#preparing-and-adding-a-signing-key).

Do you have a plan to support it?

ref
- https://www.terraform.io/registry/providers/publishing#preparing-and-adding-a-signing-key
- https://github.com/hashicorp/terraform-docs-common/blob/main/website/docs/registry/providers/publishing.mdx

**Comment by MasonM** [comment]
FYI: I entered a PR that adds ECC support: https://github.com/hashicorp/terraform/pull/32056

I'm not sure if Hashicorp will accept that change, though.

**Comment by rkoron007** [comment]
There is a more comprehensive version of this conversation happening in this issue: https://github.com/hashicorp/terraform/pull/32056, so I'm going to close this one for now.
