### ISSUE TITLE
localterraform.com is no longer TFE only..?

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-docs-common#293]
as per the changes in 1.4 ([release notes](https://github.com/hashicorp/terraform/blob/v1.4/CHANGELOG.md#140-march-08-2023)) it seems localterraform.com is no longer TFE only and [the documentation](https://developer.hashicorp.com/terraform/cloud-docs/registry/using#generic-hostname-terraform-enterprise) should be updated to reflect this.

**Comment by BrianMMcClain** [comment]
Hi Andy! Apologies for not updating you on this, we've updated the documentation as you mentioned as a part of #334, so I'll mark this as closed. Thanks again for pointing this out!
