### ISSUE TITLE
Lacking proper navigation in official documentation

### ISSUE THREAD

**Issue by anilkumarmyla** [hashicorp/terraform-docs-common#317]
The documentation at https://developer.hashicorp.com/terraform/docs lacks proper navigation.
There are atleast 3 different ways to navigate the documentation, one from top nav, one from side bar and one from within the page (if this page is an index page)

As a first time user to terraform, I'd like to be able to properly read through documentation in a sequential manner ex: Prev, Next  at the bottom of each page. The current documentation lacks this and I keep navigating pages repetitively selecting from top nav and side nav loosing my way constantly and get confused and lose interest

**Comment by judithpatudith** [comment]
Hi thank you for your report! I'll share it with the platform team. It's always helpful to hear how users want to navigate our docs. If you'd like to get started I'd encourage you to follow our [tutorials](https://developer.hashicorp.com/terraform/tutorials), which are organized more sequentially and geared toward learners. Choose the get started path for your preferred cloud provider! Hope this helps!

**Comment by rkoron007** [comment]
Hello @anilkumarmyla! 👋 I hope the [tutorials](https://developer.hashicorp.com/terraform/tutorials) experience better matched what you were looking for. I'm going to close this ticket for now, but please feel free to reopen it if there is something else you'd like to add!
