### ISSUE TITLE
Integrations > Custom Framework vs Custom SDK

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/terraform-docs-common#345]
I'm unable to locate this documentation in the GH repos, although I'm sure it's here somewhere.

I went looking for docs on writing a custom TF provider, and found https://developer.hashicorp.com/terraform/tutorials/providers. In the left side gutter under "Integrations" are two nearly identical looking options for custom providers: "Custom Framework Providers" and "Custom SDK Providers". The description of both only varies in the name/title. It's entirely unclear why both are there and which to use. Screenshots attached for reference.

It's not until I went hunting for the answer that I found [another page](https://developer.hashicorp.com/terraform/plugin/framework-benefits) under "plugins" that explains the difference. It says

> SDKv2 is the prior SDK that many existing providers use. It is maintained for Terraform versions 1.x and earlier, but we have stopped most feature development so we can focus on improving the framework.

To alleviate confusion and help developers move to use (or start with) the Plugin Framework, this description/explanation/suggestion above the [tutorial TOC](https://developer.hashicorp.com/terraform/tutorials/providers) should include some form of the above statement making it clear that the _SDK_ is not preferred.

![Screenshot 2023-05-08 at 12 59 13](https://user-images.githubusercontent.com/5077610/236897800-5471615f-a634-40d9-974b-cbeaf98a1ca2.png)
![Screenshot 2023-05-08 at 12 59 22](https://user-images.githubusercontent.com/5077610/236897811-7a2560b1-dc9e-40df-a924-af491f31dfc2.png)

**Comment by bflad** [comment]
Hi @rjhornsby 👋 Thank you for raising this issue as the tutorial content is not open source at this time.

It's a great idea that these tutorials should be more prescriptive about the preference of framework provider development over SDK provider development. We had planned on updating each the SDK tutorials to have a callout pointing to the framework tutorials with similar text to what you found, but I'm personally unsure the status of those tutorial updates. I will followup internally to ensure these updates occur to reduce confusion.

Out of curiosity, I'm wondering if:

> I went looking for docs on writing a custom TF provider, and found [https://developer.hashicorp.com/terraform/tutorials/provider](https://developer.hashicorp.com/terraform/tutorials/providers)

Was this through a search engine or similar? We would definitely love to point developers at the framework tutorials where possible and insight into how they might still be pointed at the older tutorials is greatly appreciated.

Thanks again!

**Comment by bflad** [comment]
Ah ha, it turns out those updates did happen to the individual tutorial pages (e.g. the callout box near the top of https://developer.hashicorp.com/terraform/tutorials/providers/provider-use) but not the collection page. I'll see what can happen here -- the collection page content might be a little more limited in what can be put there, so it might wind up being normal text instead of a callout.

**Comment by rjhornsby** [comment]
> Was this through a search engine or similar? 

IIRC it was a Google search result, but now I can't seem to figure out what terms I used or how I ended up on that specific page. I can see where I was trying to figure out the difference between the framework and the SDK, but not how I landed on the page that led me to trying to sort that out. Sorry that's not helpful.

> it might wind up being normal text instead of a callout.

That seems fine. Google is really good about search results for deprecated APIs, SDKs, etc showing up near the top unless you're super specific. I end up hitting this constantly with AWS documentation. So any additional remarks on the page - callout or otherwise - that say "hey, btw, we suggest the Framework" would be helpful.

**Comment by bflad** [comment]
The additional information is very appreciated, thanks so much @rjhornsby 👍

**Comment by bflad** [comment]
All set! https://developer.hashicorp.com/terraform/tutorials/providers

> In these tutorials, learn how Terraform interacts with APIs and write a provider based on the prior plugin SDK. To create a new Terraform provider, please follow the Custom Framework Providers tutorials instead.

Thank you again.
