### ISSUE TITLE
Incorrect attribute paths in table for variable set create method

### ISSUE THREAD

**Issue by s16tom** [hashicorp/terraform-docs-common#388]
In the variable sets documentation (https://github.com/hashicorp/terraform-website/blob/master/content/cloud-docs/api-docs/variable-sets.mdx) the table that specifies the required attributes doesn't quite line up with the payload below (the payload is correct).

The table lists the following fields:

data.name
data.description.
data.global

They should actually be:

data.attributes.name
data.attributes.description.
data.attributes.global

**Comment by rkoron007** [comment]
Closing this Github issue since we have updated our documentation in PR https://github.com/hashicorp/terraform-docs-common/pull/704.

Thank you for submitting this issue and making our docs better! ✨
