### ISSUE TITLE
Page titles and meta descriptions missing from registry site

### ISSUE THREAD

**Issue by williamoconnorme** [hashicorp/terraform-docs-common#408]
Web pages within the Terraform registry site no longer have unique / relevant page titles or meta descriptions. All pages have the title "Terraform Registry"

This is resulting in pages no longer being searchable in Google Search.

An example of this would be: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_fabric_cluster

If you google the URL or resource name it does not appear in search.

![image](https://github.com/hashicorp/terraform-docs-common/assets/978081/541a9f17-0028-4f9b-9bcf-8bb4986b6b4f)

**Comment by rkoron007** [comment]
Hello @williamoconnorme! I'm so sorry for the late response here, but unfortunately, this is not the best place to file this issue. The registry repository is private, so I'd recommend emailing the registry team at `terraform-registry@hashicorp.com` to submit feedback. I'm going to close this issue for now, but please let me know if I can help with anything else in the future!
