### ISSUE TITLE
update run states for final states comprehensively

### ISSUE THREAD

**Issue by abuxton** [hashicorp/terraform-docs-common#437]
https://github.com/hashicorp/terraform-docs-common/blob/main/website/docs/cloud-docs/api-docs/run.mdx

update the table of run states, to comprehensively and consistently call out those states that are considered final states

**Comment by rkoron007** [comment]
Hi @abuxton! 👋 Checking the page now it appears the final states have been labelled (several stages like `planned_and_finished` say "This is a final state."), so I'm assuming this is now complete and I'm going to close this issue. Please let me know if we need to reopen it though!
