### ISSUE TITLE
Terraform Cloud - Org Settings / Security / Authentication not documented?

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-docs-common#453]
Terraform Cloud org settings have session timeout settings that do not appear to be documented in any of the terraform cloud docs.

Located in TFC org settings, Authentication (Security subhead)

User Sessions
You can make changes here that will affect the sessions of all users in this organization.

These should be documented.

**Comment by leizerbeam** [comment]
sent a response here https://hashicorp.slack.com/archives/CPC3J8B8C/p1695662171834629?thread_ts=1693334773.648969&cid=CPC3J8B8C
