### ISSUE TITLE
website/docs/cloud-docs/api-docs/team-tokens.mdx does not document GET call

### ISSUE THREAD

**Issue by thomashashi** [hashicorp/terraform-docs-common#480]
The Team Token API documentation page does not show that you can call `GET /teams/:team_id/authentication-token` to see if an team has an existing API token, and, if the token does exist, when it was created and by whom.

This appears to be the call `app.terraform.io` calls when you go to `https://app.terraform.io/app/:organization/settings/team/:team_id` to display the "Team API Token" section.

**Comment by JarrettSpiker** [comment]
This has been added to the API docs by #703 , thanks for pointing it out!
