### ISSUE TITLE
drift detection documentation typo

### ISSUE THREAD

**Issue by quixoticmonk** [hashicorp/terraform-docs-common#592]
# Description

The documentation around [Drift Detection](https://developer.hashicorp.com/terraform/cloud-docs/workspaces/health#drift-detection) includes this statement:

```
Configuration drift occurs when changes are made outside Terrafoto's regular process, 
leading to inconsistencies between the remote objects and your configured infrastructure.
```

Assuming this is supposed to be `Terraform's` than `Terrafoto's`.

**Comment by rkoron007** [comment]
Hello! Thank you so much for submitting an issue on this! Apologies for the late response here, but it looks like someone else fixed this typo before I got to it. So, I'm going to close this issue for now, thank you so much for catching this, though! ✨
