### ISSUE TITLE
Behavior Changes in Filter for Provider Documentation

### ISSUE THREAD

**Issue by bgshacklett** [hashicorp/terraform-docs-common#630]
Apologies if this is the wrong place to raise this (directions to the right place would be appreciated in this case).

Some time ago, the `filter` feature of the provider documentation started including results which are seemingly unrelated to the value entered in the filter field.

For example, the below screenshot shows completely unrelated resources showing up when attempting to filter on "aws_instance":

<img width="355" alt="image" src="https://github.com/hashicorp/terraform-docs-common/assets/583359/66a7adce-cf8a-473a-a624-7e5ce3641490">

**Comment by rkoron007** [comment]
Hello @bgshacklett! I'm so sorry for the late response here, but unfortunately, this is not the best place to file this issue. I'd recommend emailing the registry team at `terraform-registry@hashicorp.com` to submit feedback on the registry. I'm going to close this issue for now, but please let me know if I can help with anything else in the future! ✨
