### ISSUE TITLE
Private Registry Documentation - broken link

### ISSUE THREAD

**Issue by bpelikan** [hashicorp/terraform-docs-common#668]
Documentation page: [Private Registry > Managing Usage](https://developer.hashicorp.com/terraform/cloud-docs/registry#managing-usage)

> You can even require that all of those modules use recent versions with a policy like [this example on GitHub](https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/cloud-agnostic/http-examples/use-recent-versions-from-pmr.sentinel).

Example points to a non-existent file: 
https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/cloud-agnostic/http-examples/use-recent-versions-from-pmr.sentinel
Based on [information](https://github.com/hashicorp/terraform-guides/tree/master/governance/third-generation) the file has been moved to: 
https://github.com/hashicorp/terraform-sentinel-policies/blob/main/cloud-agnostic/http-examples/use-recent-versions-from-pmr.sentinel

**Comment by rkoron007** [comment]
Fixed this link in https://github.com/hashicorp/terraform-docs-common/pull/677, so I'm going to close this issue. Thank you so much for catching this! ✨
