### ISSUE TITLE
Question: What is 'resource-count' in the context of the workspace creation endpoint payload

### ISSUE THREAD

**Issue by MatthewJohn** [hashicorp/terraform-docs-common#86]
The workspace creation endpoint has an undocumented 'resource-count' attribute.
This attribute does not appear in the list of attributes, but is included in each of the example payloads.

I can't see how creating a new workspace could/should contain this attribute or how the value would be calculated to pass to it, since at the point of creation, there wouldn't be any resources (at least 'resources' from a Terraform concept - but maybe this is a different type of resource?)

Any advice would be much appreciated - since it's included in both of the examples, I assume it's not a mistake, but happy to submit a PR to remove if it's incorrectly there :)

Many thanks

**Comment by rkoron007** [comment]
Closing this Github issue since we have updated our documentation in PR https://github.com/hashicorp/terraform-docs-common/pull/705.

Thank you for submitting this issue and making our docs better! ✨
